### PR TITLE
feat: add custom operators

### PR DESCRIPTION
**Pull request by Darkein**
Add custom operators to allow users to extend functionality.

It should allow you to do something like the following:

```ts
@Crud({
  ...
  operators: {
    custom: {
      <operator key>: (field: string, param: string) => <returns a string>
    }
  }
})
```
so, for an example like the following:
```ts
@Crud({
  ...
  operators: {
    custom: {
      intersects: (field: string, param: string) => `ST_Intersects(${field}, ST_GeomFromGeoJSON(:${param}))`
    }
  }
})
```
You should be able to do something like: `?filter=geom||intersects||<some geojson>` in order to filter the entries that actually intersect that geojson.

### CODE REVIEW

**Review by rewiko — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by rewiko** [comment]
Available in version [5.1.0](https://www.npmjs.com/package/@rewiko/crud).

**Comment by Darkein** [comment]
you're welcome, thanks you !

**Comment by sgClaudia98** [comment]
@Darkein @rewiko who can accept this change plz https://github.com/nestjsx/crud/pull/546

**Comment by rewiko** [comment]
The upstream repo nestjsx/crud is not maintained anymore (waiting for credentials from the maintainer to publish the new version)
I have forked the repo and merged the fix you are looking for. 

You can use https://www.npmjs.com/package/@rewiko/crud package which contains the fix.

**Comment by iflairritesh** [comment]
> Add custom operators to allow users to extend functionality.
> 
> It should allow you to do something like the following:
> 
> ```ts
> @Crud({
>   ...
>   operators: {
>     custom: {
>       <operator key>: (field: string, param: string) => <returns a string>
>     }
>   }
> })
> ```
> 
> so, for an example like the following:
> 
> ```ts
> @Crud({
>   ...
>   operators: {
>     custom: {
>       intersects: (field: string, param: string) => `ST_Intersects(${field}, ST_GeomFromGeoJSON(:${param}))`
>     }
>   }
> })
> ```
> 
> You should be able to do something like: `?filter=geom||intersects||<some geojson>` in order to filter the entries that actually intersect that geojson.

I have one array column in the postgres database which stores data like {3,7,41,9}

I have applied custom operator like below
operators: {
    custom: {
      //any: (field: string, param: string) => `${param} = ANY(${field})`,
      any: {
        query: (field: string, param: string) => `${param} = ANY(${field})`,
        isArray: true, // optional
      },
    },
  },
  But it still prepares Query like this
  AND "BigpdfAdvertisement"."languages" = $5) -- PARAMETERS: ["Upload","Active","2025-10-08T00:00:00.000Z","2025-10-08T00:00:00.000Z",[2]]
  Is must take the query as i defied for the operator, Am i doing anything wrong?

**Pull request merged**
